config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :recipes, only: %i[index show]
  root to: 'recipes#index'
  match '/:status', to: 'errors#show', constraints: { status: /\d{3}/ }, via: :all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def show
    # render the generic error page
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Rails.cache.fetch('recipes/all', expires_in: 10.minutes) do
      Recipe::Operation::GetAll.call[:collection] || []
    end
  end

  def show
    @recipe = Rails.cache.fetch("recipe/single#{params[:id]}", expires_in: 10.minutes) do
      Recipe::Operation::GetOne.call(id: params[:id])[:response]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = %i[hard_wrap autolink no_intra_emphasis fenced_code_blocks]
    sanitize(Markdown.new(text, *options).to_html)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "inter-font" %>
    <%= stylesheet_link_tag "tailwind" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.slim
- if @recipes.blank?
  .flex.justify-center.items-center.h-screen
    .p-4.bg-yellow-500
      = 'No recipes to show'
- else
  .m-auto.max-w-5xl
    - @recipes.each do |recipe|
      .flex.p-6
        = link_to recipe_path(recipe.id) do
          = image_tag(recipe.photo.url, title: recipe.photo.title, width: "100%", class: 'rounded-xl')
          .font-bold.text-center
            = recipe.title

app/views/recipes/show.html.slim
- if @recipe.blank?
  .flex.justify-center.items-center.h-screen
    .p-4.bg-yellow-500
      = 'The recipe does not exist'
- else
  .m-auto.max-w-5xl.pb-32
    = image_tag(@recipe.photo.url, title: @recipe.photo.title, width: "100%", class: 'rounded-xl mt-10')
    .font-bold.text-center
      = @recipe.title
    .p-4.bg-gray-100.rounded.mt-10
      = markdown @recipe.description
    .mt-4.font-bold.mb-2
      = 'Chef: '
      = @recipe.fields[:chef]&.name || 'Not available'
    - @recipe.fields[:tags]&.each do |tag|
      .p-1.mr-2.bg-yellow-400.rounded.inline-block.font-bold.text-sm
        = tag.name